# Generated by Django 5.0.4 on 2024-09-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepost',
            name='service',
        ),
    ]
