# Generated by Django 5.0.4 on 2024-09-06 19:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_servicepost_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
