# Generated by Django 5.0.4 on 2024-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rating_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='service_providers'),
        ),
    ]
