# Generated by Django 5.0.4 on 2024-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_serviceprovider_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='description',
            field=models.TextField(),
        ),
    ]
