# Generated by Django 5.0.4 on 2024-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_event_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Completed', 'Completed'), ('pending', 'Pending')], default='draft', max_length=10),
        ),
    ]
